#!/bin/bash

OS=$(uname)

if [[ "$OS" == "Linux" ]]; then
    echo "You are running on a Linux system."
elif [[ "$OS" == "Darwin" ]]; then
    echo "You are running on a macOS system."
elif [[ "$OS" == "CYGWIN"* || "$OS" == "MINGW"* ]]; then
    echo "You are running on a Windows system (via Cygwin or MinGW)."
else
    echo "Unknown operating system: $OS"
fi

while true; do
	read -p "Choose package manager (pip or conda): " pm
	if [[ "$pm" == "pip" || "$choice" == "conda" ]]; then
		pm=${pm}
		break
	else
		echo "Invalid input. Try again."
    	fi








	
